# Generated by Django 5.0.3 on 2024-03-18 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_tag_rename_text_quote_quote_remove_quote_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='bio',
            new_name='description',
        ),
    ]
