# Generated by Django 5.0.3 on 2024-03-18 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_rename_bio_author_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='fullname',
        ),
    ]
