# Generated by Django 5.0.3 on 2024-03-18 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_rename_name_author_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='birth_date',
            new_name='born_date',
        ),
    ]
